// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"go.uber.org/mock/gomock"
)

// MockEC2DescribeImagesClientInterface is a mock of EC2DescribeImagesClientInterface interface.
type MockEC2DescribeImagesClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEC2DescribeImagesClientInterfaceMockRecorder
	isgomock struct{}
}

// MockEC2DescribeImagesClientInterfaceMockRecorder is the mock recorder for MockEC2DescribeImagesClientInterface.
type MockEC2DescribeImagesClientInterfaceMockRecorder struct {
	mock *MockEC2DescribeImagesClientInterface
}

// NewMockEC2DescribeImagesClientInterface creates a new mock instance.
func NewMockEC2DescribeImagesClientInterface(ctrl *gomock.Controller) *MockEC2DescribeImagesClientInterface {
	mock := &MockEC2DescribeImagesClientInterface{ctrl: ctrl}
	mock.recorder = &MockEC2DescribeImagesClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2DescribeImagesClientInterface) EXPECT() *MockEC2DescribeImagesClientInterfaceMockRecorder {
	return m.recorder
}

// DescribeImages mocks base method.
func (m *MockEC2DescribeImagesClientInterface) DescribeImages(context1 context.Context, describeImagesInput *ec2.DescribeImagesInput, fns ...func(*ec2.Options)) (*ec2.DescribeImagesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeImagesInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeImages", varargs...)
	describeImagesOutput, _ := ret[0].(*ec2.DescribeImagesOutput)
	err, _ := ret[1].(error)
	return describeImagesOutput, err
}

// DescribeImages indicates an expected call of DescribeImages.
func (mr *MockEC2DescribeImagesClientInterfaceMockRecorder) DescribeImages(context1, describeImagesInput any,
	fns ...any) *MockEC2DescribeImagesClientInterfaceDescribeImagesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeImagesInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeImages", reflect.TypeOf((*MockEC2DescribeImagesClientInterface)(nil).DescribeImages), varargs...)
	return &MockEC2DescribeImagesClientInterfaceDescribeImagesCall{Call: call}
}

// MockEC2DescribeImagesClientInterfaceDescribeImagesCall wrap *gomock.Call
type MockEC2DescribeImagesClientInterfaceDescribeImagesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEC2DescribeImagesClientInterfaceDescribeImagesCall) Return(describeImagesOutput *ec2.DescribeImagesOutput, err error) *MockEC2DescribeImagesClientInterfaceDescribeImagesCall {
	c.Call = c.Call.Return(describeImagesOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEC2DescribeImagesClientInterfaceDescribeImagesCall) Do(f func(context.Context, *ec2.DescribeImagesInput, ...func(*ec2.Options)) (*ec2.DescribeImagesOutput, error)) *MockEC2DescribeImagesClientInterfaceDescribeImagesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEC2DescribeImagesClientInterfaceDescribeImagesCall) DoAndReturn(f func(context.Context, *ec2.DescribeImagesInput, ...func(*ec2.Options)) (*ec2.DescribeImagesOutput, error)) *MockEC2DescribeImagesClientInterfaceDescribeImagesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
