// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"go.uber.org/mock/gomock"
)

// MockEC2DescribeSnapshotsClientInterface is a mock of EC2DescribeSnapshotsClientInterface interface.
type MockEC2DescribeSnapshotsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEC2DescribeSnapshotsClientInterfaceMockRecorder
	isgomock struct{}
}

// MockEC2DescribeSnapshotsClientInterfaceMockRecorder is the mock recorder for MockEC2DescribeSnapshotsClientInterface.
type MockEC2DescribeSnapshotsClientInterfaceMockRecorder struct {
	mock *MockEC2DescribeSnapshotsClientInterface
}

// NewMockEC2DescribeSnapshotsClientInterface creates a new mock instance.
func NewMockEC2DescribeSnapshotsClientInterface(ctrl *gomock.Controller) *MockEC2DescribeSnapshotsClientInterface {
	mock := &MockEC2DescribeSnapshotsClientInterface{ctrl: ctrl}
	mock.recorder = &MockEC2DescribeSnapshotsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2DescribeSnapshotsClientInterface) EXPECT() *MockEC2DescribeSnapshotsClientInterfaceMockRecorder {
	return m.recorder
}

// DescribeSnapshots mocks base method.
func (m *MockEC2DescribeSnapshotsClientInterface) DescribeSnapshots(context1 context.Context, describeSnapshotsInput *ec2.DescribeSnapshotsInput, fns ...func(*ec2.Options)) (*ec2.DescribeSnapshotsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeSnapshotsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeSnapshots", varargs...)
	describeSnapshotsOutput, _ := ret[0].(*ec2.DescribeSnapshotsOutput)
	err, _ := ret[1].(error)
	return describeSnapshotsOutput, err
}

// DescribeSnapshots indicates an expected call of DescribeSnapshots.
func (mr *MockEC2DescribeSnapshotsClientInterfaceMockRecorder) DescribeSnapshots(context1, describeSnapshotsInput any,
	fns ...any) *MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeSnapshotsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSnapshots", reflect.TypeOf((*MockEC2DescribeSnapshotsClientInterface)(nil).DescribeSnapshots), varargs...)
	return &MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall{Call: call}
}

// MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall wrap *gomock.Call
type MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall) Return(describeSnapshotsOutput *ec2.DescribeSnapshotsOutput, err error) *MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall {
	c.Call = c.Call.Return(describeSnapshotsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall) Do(f func(context.Context, *ec2.DescribeSnapshotsInput, ...func(*ec2.Options)) (*ec2.DescribeSnapshotsOutput, error)) *MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall) DoAndReturn(f func(context.Context, *ec2.DescribeSnapshotsInput, ...func(*ec2.Options)) (*ec2.DescribeSnapshotsOutput, error)) *MockEC2DescribeSnapshotsClientInterfaceDescribeSnapshotsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
