// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"go.uber.org/mock/gomock"
)

// MockEC2DescribeVolumesClientInterface is a mock of EC2DescribeVolumesClientInterface interface.
type MockEC2DescribeVolumesClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEC2DescribeVolumesClientInterfaceMockRecorder
	isgomock struct{}
}

// MockEC2DescribeVolumesClientInterfaceMockRecorder is the mock recorder for MockEC2DescribeVolumesClientInterface.
type MockEC2DescribeVolumesClientInterfaceMockRecorder struct {
	mock *MockEC2DescribeVolumesClientInterface
}

// NewMockEC2DescribeVolumesClientInterface creates a new mock instance.
func NewMockEC2DescribeVolumesClientInterface(ctrl *gomock.Controller) *MockEC2DescribeVolumesClientInterface {
	mock := &MockEC2DescribeVolumesClientInterface{ctrl: ctrl}
	mock.recorder = &MockEC2DescribeVolumesClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2DescribeVolumesClientInterface) EXPECT() *MockEC2DescribeVolumesClientInterfaceMockRecorder {
	return m.recorder
}

// DescribeVolumes mocks base method.
func (m *MockEC2DescribeVolumesClientInterface) DescribeVolumes(context1 context.Context, describeVolumesInput *ec2.DescribeVolumesInput, fns ...func(*ec2.Options)) (*ec2.DescribeVolumesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeVolumesInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeVolumes", varargs...)
	describeVolumesOutput, _ := ret[0].(*ec2.DescribeVolumesOutput)
	err, _ := ret[1].(error)
	return describeVolumesOutput, err
}

// DescribeVolumes indicates an expected call of DescribeVolumes.
func (mr *MockEC2DescribeVolumesClientInterfaceMockRecorder) DescribeVolumes(context1, describeVolumesInput any,
	fns ...any) *MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeVolumesInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeVolumes", reflect.TypeOf((*MockEC2DescribeVolumesClientInterface)(nil).DescribeVolumes), varargs...)
	return &MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall{Call: call}
}

// MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall wrap *gomock.Call
type MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall) Return(describeVolumesOutput *ec2.DescribeVolumesOutput, err error) *MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall {
	c.Call = c.Call.Return(describeVolumesOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall) Do(f func(context.Context, *ec2.DescribeVolumesInput, ...func(*ec2.Options)) (*ec2.DescribeVolumesOutput, error)) *MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall) DoAndReturn(f func(context.Context, *ec2.DescribeVolumesInput, ...func(*ec2.Options)) (*ec2.DescribeVolumesOutput, error)) *MockEC2DescribeVolumesClientInterfaceDescribeVolumesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
