// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"go.uber.org/mock/gomock"
)

// MockEC2DescribeSecurityGroupsClientInterface is a mock of EC2DescribeSecurityGroupsClientInterface interface.
type MockEC2DescribeSecurityGroupsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEC2DescribeSecurityGroupsClientInterfaceMockRecorder
	isgomock struct{}
}

// MockEC2DescribeSecurityGroupsClientInterfaceMockRecorder is the mock recorder for MockEC2DescribeSecurityGroupsClientInterface.
type MockEC2DescribeSecurityGroupsClientInterfaceMockRecorder struct {
	mock *MockEC2DescribeSecurityGroupsClientInterface
}

// NewMockEC2DescribeSecurityGroupsClientInterface creates a new mock instance.
func NewMockEC2DescribeSecurityGroupsClientInterface(ctrl *gomock.Controller) *MockEC2DescribeSecurityGroupsClientInterface {
	mock := &MockEC2DescribeSecurityGroupsClientInterface{ctrl: ctrl}
	mock.recorder = &MockEC2DescribeSecurityGroupsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2DescribeSecurityGroupsClientInterface) EXPECT() *MockEC2DescribeSecurityGroupsClientInterfaceMockRecorder {
	return m.recorder
}

// DescribeSecurityGroups mocks base method.
func (m *MockEC2DescribeSecurityGroupsClientInterface) DescribeSecurityGroups(context1 context.Context, describeSecurityGroupsInput *ec2.DescribeSecurityGroupsInput, fns ...func(*ec2.Options)) (*ec2.DescribeSecurityGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeSecurityGroupsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeSecurityGroups", varargs...)
	describeSecurityGroupsOutput, _ := ret[0].(*ec2.DescribeSecurityGroupsOutput)
	err, _ := ret[1].(error)
	return describeSecurityGroupsOutput, err
}

// DescribeSecurityGroups indicates an expected call of DescribeSecurityGroups.
func (mr *MockEC2DescribeSecurityGroupsClientInterfaceMockRecorder) DescribeSecurityGroups(context1, describeSecurityGroupsInput any,
	fns ...any) *MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeSecurityGroupsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSecurityGroups", reflect.TypeOf((*MockEC2DescribeSecurityGroupsClientInterface)(nil).DescribeSecurityGroups), varargs...)
	return &MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall{Call: call}
}

// MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall wrap *gomock.Call
type MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall) Return(describeSecurityGroupsOutput *ec2.DescribeSecurityGroupsOutput, err error) *MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall {
	c.Call = c.Call.Return(describeSecurityGroupsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall) Do(f func(context.Context, *ec2.DescribeSecurityGroupsInput, ...func(*ec2.Options)) (*ec2.DescribeSecurityGroupsOutput, error)) *MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall) DoAndReturn(f func(context.Context, *ec2.DescribeSecurityGroupsInput, ...func(*ec2.Options)) (*ec2.DescribeSecurityGroupsOutput, error)) *MockEC2DescribeSecurityGroupsClientInterfaceDescribeSecurityGroupsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
