// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/kms"
	"go.uber.org/mock/gomock"
)

// MockKMSListKeysClientInterface is a mock of KMSListKeysClientInterface interface.
type MockKMSListKeysClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockKMSListKeysClientInterfaceMockRecorder
	isgomock struct{}
}

// MockKMSListKeysClientInterfaceMockRecorder is the mock recorder for MockKMSListKeysClientInterface.
type MockKMSListKeysClientInterfaceMockRecorder struct {
	mock *MockKMSListKeysClientInterface
}

// NewMockKMSListKeysClientInterface creates a new mock instance.
func NewMockKMSListKeysClientInterface(ctrl *gomock.Controller) *MockKMSListKeysClientInterface {
	mock := &MockKMSListKeysClientInterface{ctrl: ctrl}
	mock.recorder = &MockKMSListKeysClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKMSListKeysClientInterface) EXPECT() *MockKMSListKeysClientInterfaceMockRecorder {
	return m.recorder
}

// ListKeys mocks base method.
func (m *MockKMSListKeysClientInterface) ListKeys(context1 context.Context, listKeysInput *kms.ListKeysInput, fns ...func(*kms.Options)) (*kms.ListKeysOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, listKeysInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListKeys", varargs...)
	listKeysOutput, _ := ret[0].(*kms.ListKeysOutput)
	err, _ := ret[1].(error)
	return listKeysOutput, err
}

// ListKeys indicates an expected call of ListKeys.
func (mr *MockKMSListKeysClientInterfaceMockRecorder) ListKeys(context1, listKeysInput any,
	fns ...any) *MockKMSListKeysClientInterfaceListKeysCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, listKeysInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeys", reflect.TypeOf((*MockKMSListKeysClientInterface)(nil).ListKeys), varargs...)
	return &MockKMSListKeysClientInterfaceListKeysCall{Call: call}
}

// MockKMSListKeysClientInterfaceListKeysCall wrap *gomock.Call
type MockKMSListKeysClientInterfaceListKeysCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKMSListKeysClientInterfaceListKeysCall) Return(listKeysOutput *kms.ListKeysOutput, err error) *MockKMSListKeysClientInterfaceListKeysCall {
	c.Call = c.Call.Return(listKeysOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKMSListKeysClientInterfaceListKeysCall) Do(f func(context.Context, *kms.ListKeysInput, ...func(*kms.Options)) (*kms.ListKeysOutput, error)) *MockKMSListKeysClientInterfaceListKeysCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKMSListKeysClientInterfaceListKeysCall) DoAndReturn(f func(context.Context, *kms.ListKeysInput, ...func(*kms.Options)) (*kms.ListKeysOutput, error)) *MockKMSListKeysClientInterfaceListKeysCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
