// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/kms"
	"go.uber.org/mock/gomock"
)

// MockKMSListAliasesClientInterface is a mock of KMSListAliasesClientInterface interface.
type MockKMSListAliasesClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockKMSListAliasesClientInterfaceMockRecorder
	isgomock struct{}
}

// MockKMSListAliasesClientInterfaceMockRecorder is the mock recorder for MockKMSListAliasesClientInterface.
type MockKMSListAliasesClientInterfaceMockRecorder struct {
	mock *MockKMSListAliasesClientInterface
}

// NewMockKMSListAliasesClientInterface creates a new mock instance.
func NewMockKMSListAliasesClientInterface(ctrl *gomock.Controller) *MockKMSListAliasesClientInterface {
	mock := &MockKMSListAliasesClientInterface{ctrl: ctrl}
	mock.recorder = &MockKMSListAliasesClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKMSListAliasesClientInterface) EXPECT() *MockKMSListAliasesClientInterfaceMockRecorder {
	return m.recorder
}

// ListAliases mocks base method.
func (m *MockKMSListAliasesClientInterface) ListAliases(context1 context.Context, listAliasesInput *kms.ListAliasesInput, fns ...func(*kms.Options)) (*kms.ListAliasesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, listAliasesInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAliases", varargs...)
	listAliasesOutput, _ := ret[0].(*kms.ListAliasesOutput)
	err, _ := ret[1].(error)
	return listAliasesOutput, err
}

// ListAliases indicates an expected call of ListAliases.
func (mr *MockKMSListAliasesClientInterfaceMockRecorder) ListAliases(context1, listAliasesInput any,
	fns ...any) *MockKMSListAliasesClientInterfaceListAliasesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, listAliasesInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAliases", reflect.TypeOf((*MockKMSListAliasesClientInterface)(nil).ListAliases), varargs...)
	return &MockKMSListAliasesClientInterfaceListAliasesCall{Call: call}
}

// MockKMSListAliasesClientInterfaceListAliasesCall wrap *gomock.Call
type MockKMSListAliasesClientInterfaceListAliasesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKMSListAliasesClientInterfaceListAliasesCall) Return(listAliasesOutput *kms.ListAliasesOutput, err error) *MockKMSListAliasesClientInterfaceListAliasesCall {
	c.Call = c.Call.Return(listAliasesOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKMSListAliasesClientInterfaceListAliasesCall) Do(f func(context.Context, *kms.ListAliasesInput, ...func(*kms.Options)) (*kms.ListAliasesOutput, error)) *MockKMSListAliasesClientInterfaceListAliasesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKMSListAliasesClientInterfaceListAliasesCall) DoAndReturn(f func(context.Context, *kms.ListAliasesInput, ...func(*kms.Options)) (*kms.ListAliasesOutput, error)) *MockKMSListAliasesClientInterfaceListAliasesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
