// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"go.uber.org/mock/gomock"
)

// MockEC2DescribeVpcsClientInterface is a mock of EC2DescribeVpcsClientInterface interface.
type MockEC2DescribeVpcsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEC2DescribeVpcsClientInterfaceMockRecorder
	isgomock struct{}
}

// MockEC2DescribeVpcsClientInterfaceMockRecorder is the mock recorder for MockEC2DescribeVpcsClientInterface.
type MockEC2DescribeVpcsClientInterfaceMockRecorder struct {
	mock *MockEC2DescribeVpcsClientInterface
}

// NewMockEC2DescribeVpcsClientInterface creates a new mock instance.
func NewMockEC2DescribeVpcsClientInterface(ctrl *gomock.Controller) *MockEC2DescribeVpcsClientInterface {
	mock := &MockEC2DescribeVpcsClientInterface{ctrl: ctrl}
	mock.recorder = &MockEC2DescribeVpcsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2DescribeVpcsClientInterface) EXPECT() *MockEC2DescribeVpcsClientInterfaceMockRecorder {
	return m.recorder
}

// DescribeVpcs mocks base method.
func (m *MockEC2DescribeVpcsClientInterface) DescribeVpcs(context1 context.Context, describeVpcsInput *ec2.DescribeVpcsInput, fns ...func(*ec2.Options)) (*ec2.DescribeVpcsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeVpcsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeVpcs", varargs...)
	describeVpcsOutput, _ := ret[0].(*ec2.DescribeVpcsOutput)
	err, _ := ret[1].(error)
	return describeVpcsOutput, err
}

// DescribeVpcs indicates an expected call of DescribeVpcs.
func (mr *MockEC2DescribeVpcsClientInterfaceMockRecorder) DescribeVpcs(context1, describeVpcsInput any,
	fns ...any) *MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeVpcsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeVpcs", reflect.TypeOf((*MockEC2DescribeVpcsClientInterface)(nil).DescribeVpcs), varargs...)
	return &MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall{Call: call}
}

// MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall wrap *gomock.Call
type MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall) Return(describeVpcsOutput *ec2.DescribeVpcsOutput, err error) *MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall {
	c.Call = c.Call.Return(describeVpcsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall) Do(f func(context.Context, *ec2.DescribeVpcsInput, ...func(*ec2.Options)) (*ec2.DescribeVpcsOutput, error)) *MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall) DoAndReturn(f func(context.Context, *ec2.DescribeVpcsInput, ...func(*ec2.Options)) (*ec2.DescribeVpcsOutput, error)) *MockEC2DescribeVpcsClientInterfaceDescribeVpcsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
