// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"go.uber.org/mock/gomock"
)

// MockEC2DescribeNetworkInterfacesClientInterface is a mock of EC2DescribeNetworkInterfacesClientInterface interface.
type MockEC2DescribeNetworkInterfacesClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEC2DescribeNetworkInterfacesClientInterfaceMockRecorder
	isgomock struct{}
}

// MockEC2DescribeNetworkInterfacesClientInterfaceMockRecorder is the mock recorder for MockEC2DescribeNetworkInterfacesClientInterface.
type MockEC2DescribeNetworkInterfacesClientInterfaceMockRecorder struct {
	mock *MockEC2DescribeNetworkInterfacesClientInterface
}

// NewMockEC2DescribeNetworkInterfacesClientInterface creates a new mock instance.
func NewMockEC2DescribeNetworkInterfacesClientInterface(ctrl *gomock.Controller) *MockEC2DescribeNetworkInterfacesClientInterface {
	mock := &MockEC2DescribeNetworkInterfacesClientInterface{ctrl: ctrl}
	mock.recorder = &MockEC2DescribeNetworkInterfacesClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2DescribeNetworkInterfacesClientInterface) EXPECT() *MockEC2DescribeNetworkInterfacesClientInterfaceMockRecorder {
	return m.recorder
}

// DescribeNetworkInterfaces mocks base method.
func (m *MockEC2DescribeNetworkInterfacesClientInterface) DescribeNetworkInterfaces(context1 context.Context, describeNetworkInterfacesInput *ec2.DescribeNetworkInterfacesInput, fns ...func(*ec2.Options)) (*ec2.DescribeNetworkInterfacesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeNetworkInterfacesInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeNetworkInterfaces", varargs...)
	describeNetworkInterfacesOutput, _ := ret[0].(*ec2.DescribeNetworkInterfacesOutput)
	err, _ := ret[1].(error)
	return describeNetworkInterfacesOutput, err
}

// DescribeNetworkInterfaces indicates an expected call of DescribeNetworkInterfaces.
func (mr *MockEC2DescribeNetworkInterfacesClientInterfaceMockRecorder) DescribeNetworkInterfaces(context1, describeNetworkInterfacesInput any,
	fns ...any) *MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeNetworkInterfacesInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeNetworkInterfaces", reflect.TypeOf((*MockEC2DescribeNetworkInterfacesClientInterface)(nil).DescribeNetworkInterfaces), varargs...)
	return &MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall{Call: call}
}

// MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall wrap *gomock.Call
type MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall) Return(describeNetworkInterfacesOutput *ec2.DescribeNetworkInterfacesOutput, err error) *MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall {
	c.Call = c.Call.Return(describeNetworkInterfacesOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall) Do(f func(context.Context, *ec2.DescribeNetworkInterfacesInput, ...func(*ec2.Options)) (*ec2.DescribeNetworkInterfacesOutput, error)) *MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall) DoAndReturn(f func(context.Context, *ec2.DescribeNetworkInterfacesInput, ...func(*ec2.Options)) (*ec2.DescribeNetworkInterfacesOutput, error)) *MockEC2DescribeNetworkInterfacesClientInterfaceDescribeNetworkInterfacesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
