// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"go.uber.org/mock/gomock"
)

// MockEC2DescribeSubnetsClientInterface is a mock of EC2DescribeSubnetsClientInterface interface.
type MockEC2DescribeSubnetsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEC2DescribeSubnetsClientInterfaceMockRecorder
	isgomock struct{}
}

// MockEC2DescribeSubnetsClientInterfaceMockRecorder is the mock recorder for MockEC2DescribeSubnetsClientInterface.
type MockEC2DescribeSubnetsClientInterfaceMockRecorder struct {
	mock *MockEC2DescribeSubnetsClientInterface
}

// NewMockEC2DescribeSubnetsClientInterface creates a new mock instance.
func NewMockEC2DescribeSubnetsClientInterface(ctrl *gomock.Controller) *MockEC2DescribeSubnetsClientInterface {
	mock := &MockEC2DescribeSubnetsClientInterface{ctrl: ctrl}
	mock.recorder = &MockEC2DescribeSubnetsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2DescribeSubnetsClientInterface) EXPECT() *MockEC2DescribeSubnetsClientInterfaceMockRecorder {
	return m.recorder
}

// DescribeSubnets mocks base method.
func (m *MockEC2DescribeSubnetsClientInterface) DescribeSubnets(context1 context.Context, describeSubnetsInput *ec2.DescribeSubnetsInput, fns ...func(*ec2.Options)) (*ec2.DescribeSubnetsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, describeSubnetsInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeSubnets", varargs...)
	describeSubnetsOutput, _ := ret[0].(*ec2.DescribeSubnetsOutput)
	err, _ := ret[1].(error)
	return describeSubnetsOutput, err
}

// DescribeSubnets indicates an expected call of DescribeSubnets.
func (mr *MockEC2DescribeSubnetsClientInterfaceMockRecorder) DescribeSubnets(context1, describeSubnetsInput any,
	fns ...any) *MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, describeSubnetsInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSubnets", reflect.TypeOf((*MockEC2DescribeSubnetsClientInterface)(nil).DescribeSubnets), varargs...)
	return &MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall{Call: call}
}

// MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall wrap *gomock.Call
type MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall) Return(describeSubnetsOutput *ec2.DescribeSubnetsOutput, err error) *MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall {
	c.Call = c.Call.Return(describeSubnetsOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall) Do(f func(context.Context, *ec2.DescribeSubnetsInput, ...func(*ec2.Options)) (*ec2.DescribeSubnetsOutput, error)) *MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall) DoAndReturn(f func(context.Context, *ec2.DescribeSubnetsInput, ...func(*ec2.Options)) (*ec2.DescribeSubnetsOutput, error)) *MockEC2DescribeSubnetsClientInterfaceDescribeSubnetsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
